version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: aplikacja_jezykowa_postgres
    environment:
      POSTGRES_USER: lingua
      POSTGRES_PASSWORD: lingua
      POSTGRES_DB: lingua_ai
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: